### ISSUE TITLE
1.0.4 有个问题

### ISSUE THREAD

**Issue by meviyysss** [sari3l/sams_helper#11]
[!] Post "https://api-sams.walmartmobile.cn/api/v1/sams/trade/settlement/commitPay": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by sari3l** [comment]
请问有具体订单内容么

**Comment by meviyysss** [comment]
发现刚刚有更新了？

**Comment by sari3l** [comment]
稍等，我重新编译一下

**Comment by meviyysss** [comment]
山姆的app确认订单页是不是改了 发现

**Comment by sari3l** [comment]
我刚下订单还是可以的呢，稍等v1.0.4在重新编译

**Comment by meviyysss** [comment]
谢谢大佬

**Comment by meviyysss** [comment]
上午好像 是这个问题  code: RECEIVER_TIME_EMPTY 收货时间为空

**Comment by sari3l** [comment]
麻烦使用最新的版本试一下呢，config.yaml不用修改

**Comment by meviyysss** [comment]
暂时不知道下单会有什么问题哈哈 辛苦大佬更新~~

**Comment by sari3l** [comment]
建议可以在空闲时间，先尝试用可下单的地址测试一下，确保整个过程是正常的
