### ISSUE TITLE
auth-token过期

### ISSUE THREAD

**Issue by hydra77** [sari3l/sams_helper#12]
同一个token在另一个python可以运行，这里鉴权显示已经过期，请问是不是因为这个也算是新设备，超过山姆账号登陆3个设备的限制？

**Comment by sari3l** [comment]
不好意思，山姆具体计算新设备的逻辑不是很清楚，建议如果代码层面无直接解决方案的话，重新登录可能会重新分配token（我还没试过）

**Comment by hydra77** [comment]
> 不好意思，山姆具体计算新设备的逻辑不是很清楚，建议如果代码层面无直接解决方案的话，重新登录可能会重新分配token（我还没试过）

好像是根据device id？

**Comment by hydra77** [comment]
更疑惑了，因为用的主页的原版go程序是可以用的，另一个python的也是可以。

**Comment by sari3l** [comment]
可以在requests.go里面直修改header看看效果

**Comment by hydra77** [comment]
> 可以在requests.go里面直修改header看看效果

emmm,直接修改后是可以了。谢谢
