### ISSUE TITLE
暴力模式下出现了收获时间为空的情况

### ISSUE THREAD

**Issue by haojianxun** [sari3l/sams_helper#13]
![image](https://user-images.githubusercontent.com/24749811/164011781-6160a463-3771-4d67-bdb6-5f31630ed02a.png)

**Comment by connermo** [comment]
嗯，一样的错误。是不是暴力模式有问题？

**Comment by sari3l** [comment]
抱歉，这个犯了一个低级错误，已准备更新
另：此错误大概率不影响提单，因为是网络崩了导致异常没有捕获

**Comment by connermo** [comment]
辛苦大佬，但是暴力是推荐开么？

**Comment by sari3l** [comment]
现在是这个样子，暴力模式如果检测到没有利用条件会自行回归到常规模式，所以一直开着也没事
