### ISSUE TITLE
go run main.go后怎么添加auth-token

### ISSUE THREAD

**Issue by huzisir** [sari3l/sams_helper#15]
一直提示[!] auth-token 可能未设置，请检查

**Comment by sari3l** [comment]
请先修改config.yaml文件

**Comment by huzisir** [comment]
不好意思，我再问个小白的问题，用什么软件修改，还是直接在github上修改了再下载代码，不是程序员不太懂，谢谢

**Comment by huzisir** [comment]
> 不好意思，我再问个小白的问题，用什么软件修改，还是直接在github上修改了再下载代码，不是程序员不太懂，谢谢

我会了，谢谢
