### ISSUE TITLE
挂机捡漏购物车会自动刷新吗？

### ISSUE THREAD

**Issue by zhoubo518** [sari3l/sams_helper#16]
老大好，麻烦问下购物车会自动刷新吗？比如购物车里所有商品都是缺货状态，但想挂机捡漏，程序会自动更新购物车里的商品吗？

**Comment by sari3l** [comment]
你好，目前集中在运力获取，所以只有刚启动以及订单有问题时会重新检查购物车

如果专注捡漏，可以自行修改main.go 并打包（以下修改会加大在网络拥挤时抢运力的难度）

原代码 line 159-169
```go
fmt.Printf("########## 获取当前可用配送时间【%s】 ###########\n", time.Now().Format("15:04:05"))
if err = session.CheckCapacity(); err != nil {
	fmt.Printf("[!] %s\n", err)
	switch err {
	case conf.CapacityFullErr, conf.LimitedErr, conf.LimitedErr1:
		time.Sleep(500 * time.Millisecond)
		goto CapacityLoop
	default:
		goto CartLoop
	}
}
```

修改为
```go
fmt.Printf("########## 获取当前可用配送时间【%s】 ###########\n", time.Now().Format("15:04:05"))
if err = session.CheckCapacity(); err != nil {
	fmt.Printf("[!] %s\n", err)
	goto CartLoop
}
```

**Comment by zhoubo518** [comment]
![image](https://user-images.githubusercontent.com/103916349/164395654-ef7ee9c9-bf9f-43ed-bb49-862b62087eb0.png)
![image](https://user-images.githubusercontent.com/103916349/164395789-a0ca8c9a-ec08-41e7-802a-767ae28ef4e2.png)
作者好，改完之后提示运行模式错误，请检查配置，不知道是什么问题。。。

**Comment by sari3l** [comment]
请确认是使用最新的config.yaml么？

**Comment by zhoubo518** [comment]
![image](https://user-images.githubusercontent.com/103916349/164420750-2b4146bb-21ca-4475-a61e-1fccd01d7fd5.png)

更新config.yaml之后正常了，谢谢提醒！
