### ISSUE TITLE
[!] open config.yaml: The system cannot find the file specified.

### ISSUE THREAD

**Issue by JIMJIMAA** [sari3l/sams_helper#19]
请问下如何解决[!] open config.yaml: The system cannot find the file specified.呢？
config.yaml 已经放在同一文件夹里了

**Comment by JIMJIMAA** [comment]
![image](https://user-images.githubusercontent.com/2133532/164648187-7ae8649c-cdc8-479b-8d88-9c65ccd6d921.png)
![image](https://user-images.githubusercontent.com/2133532/164648220-8a9fce50-1cd7-4a1b-a782-b2c182ae2db2.png)

**Comment by 51033044** [comment]
不要弄了，抢不到了

**Comment by sari3l** [comment]
```shell
> cd E:\1\
> sams_helper.exe
```
另现在山姆没有常规物品了，只有保供套餐

**Comment by funnyData** [comment]
> ```shell
> > cd E:\1\
> > sams_helper.exe
> ```
> 
> 另现在山姆没有常规物品了，只有保供套餐

那现在这个保供套餐还可以用这套代码来抢呢？如何抢呢？

**Comment by sari3l** [comment]
> > ```shell
> > > cd E:\1\
> > > sams_helper.exe
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 另现在山姆没有常规物品了，只有保供套餐
> 
> 那现在这个保供套餐还可以用这套代码来抢呢？如何抢呢？

源代码运行，同时runMode设置为2即可，因为测试效果不是很理想，没有正式上线
