### ISSUE TITLE
保供产品源代码运行

### ISSUE THREAD

**Issue by meviyysss** [sari3l/sams_helper#20]
大神 保供产品源代码运行是怎么操作呀  我现在这个页面是否已经开始抢了？

<img width="1301" alt="截屏2022-04-24 上午8 48 47" src="https://user-images.githubusercontent.com/103988517/164950994-e83d60d8-1792-490b-a470-06b9eacd3427.png">

**Comment by meviyysss** [comment]
想要套餐B  已经忽略掉A

**Comment by meviyysss** [comment]
这个会自动加入购物车 下单吗

**Comment by sari3l** [comment]
监控到有数量就会自动加入购物车并且下单，但是由于样本太小，不确定成功率
普通商品逻辑：手动加入购物车->（程序开始）检校商品有效、数量合理->运力检测->下单
保供商品逻辑：（程序开始）获取保供列表->检校商品预期、数量合理->自动加入购物车->运力检测->下单
因为步骤很多，受网络影响更大，不是很好抢所以一直没上线
可以尝试`普通商品逻辑`，直接把套餐加入购物车，运行runMode=1，这样购物车会一直检验套餐是否可以购买

**Comment by meviyysss** [comment]
没货无法加入购物车

**Comment by meviyysss** [comment]
那我现在这个页面是正常的吧 那就先这样感恩

**Comment by sari3l** [comment]
这样是正常的

> 没货无法加入购物车

前端是限制的，但是可以代码提交，可临时在main 222行添加以下代码，会把所有检测到的商品都加入购物车（这里在做黑白名单逻辑修改地方就多了，所以不想要的套餐手动购物车删除吧），确认添加后修改 runMode=1 同时重启程序

```go
var goodsListTmp []sams.AddCartGoods
for _, goods := range goodsList {
  goodsListTmp = append(goodsListTmp, goods.ToAddCartGoods())
  if err = session.AddCartGoodsInfo(goodsListTmp); err != nil {
  fmt.Printf("[!] %s\n", err)
  }
}
```

**Comment by meviyysss** [comment]
上午试了一下 可以正常自动加入购物车 并生成订单 感恩

**Comment by bellxloud** [comment]
> 上午试了一下 可以正常自动加入购物车 并生成订单 感恩

你是加了上面的代码还是没加 最后成功的
