### ISSUE TITLE
保供商品已经添加到购物车，为何获取不到有效订单

### ISSUE THREAD

**Issue by peng530** [sari3l/sams_helper#21]
![image](https://user-images.githubusercontent.com/6337311/164955240-9f6bd18d-9fc5-4ae6-b8a3-c4fdf46f19fa.png)
一直无法获取有效商品，看着不像瞬间没了，因为再来一次还是能获取保供商品

**Comment by sari3l** [comment]
可能是位置不能派送到？
1. 如果程序能跑出数量并加入购物车，请检查一下购物车里是否正常显示
2. 如果已加入购物车但是无法购买，那就是不能配送

**Comment by peng530** [comment]
> 可能是位置不能派送到？
> 
> 1. 如果程序能跑出数量并加入购物车，请检查一下购物车里是否正常显示
> 2. 如果已加入购物车但是无法购买，那就是不能配送

之前买过一单全城送的能送到，不知道现在保供的配送范围是否有变化。现在看商品是在购物车的，那可能保供的我这边配送不到？

**Comment by sari3l** [comment]
> > 可能是位置不能派送到？
> > 
> > 1. 如果程序能跑出数量并加入购物车，请检查一下购物车里是否正常显示
> > 2. 如果已加入购物车但是无法购买，那就是不能配送
> 
> 之前买过一单全城送的能送到，不知道现在保供的配送范围是否有变化。现在看商品是在购物车的，那可能保供的我这边配送不到？

如果购物车能添加，但是无法下单，一般是运力不支持，大概是山姆不配送那里了

**Comment by peng530** [comment]
> > > 可能是位置不能派送到？
> > > 
> > > 1. 如果程序能跑出数量并加入购物车，请检查一下购物车里是否正常显示
> > > 2. 如果已加入购物车但是无法购买，那就是不能配送
> > 
> > 
> > 之前买过一单全城送的能送到，不知道现在保供的配送范围是否有变化。现在看商品是在购物车的，那可能保供的我这边配送不到？
> 
> 如果购物车能添加，但是无法下单，一般是运力不支持，大概是山姆不配送那里了

好的，谢谢
