### ISSUE TITLE
抢单成功后程序不会自动停止

### ISSUE THREAD

**Issue by liubola** [sari3l/sams_helper#22]
最近抢单成功率下降了，出现了两次抢单成功后程序仍在刷新可配送时间的情况。
第一单发现的时候已经支付超时了，今天这单还好长了个心眼看了下
支付方式：沃尔玛卡
开启暴力运力模式
极速达

**Comment by sari3l** [comment]
1. 已经支付这个问题可以通过设置提醒进行避免
2. 刷新问题我再看一下，因为暴力运力模式原本就有些复杂
另：有极速达了？😭

**Comment by liubola** [comment]
> 1. 已经支付这个问题可以通过设置提醒进行避免
> 2. 刷新问题我再看一下，因为暴力运力模式原本就有些复杂
>    另：有极速达了？😭

坐标普陀，有前置仓，可以下单极速达。。

**Comment by sari3l** [comment]
找到原因了，暴力运力模式下系统承认订单，但是返回内容 "isSuccess":false，所以程序认为没完成

**Comment by sari3l** [comment]
已修正，待观察
