### ISSUE TITLE
拜托大佬 能不能改一下这个保供关键词排除的方法

### ISSUE THREAD

**Issue by JONREAN2** [sari3l/sams_helper#23]
能提供一下 这个只想要 鲜食套餐 修改方法吗
对go 确实无能为力啊
感觉排除法实在不太好啊
名字天天改，今天全抢了日用套餐

**Comment by sari3l** [comment]
我加个白名单吧

**Comment by JONREAN2** [comment]
> * v1.0.6 支持黑白名单

太感谢了 替我们的上海朋友
太感谢了
