### ISSUE TITLE
5e853ab 无法获取购物车信息

### ISSUE THREAD

**Issue by robinspt** [sari3l/sams_helper#24]
前一版还是正常的
![image](https://user-images.githubusercontent.com/46096863/165038767-2ed80fca-9b7c-4e2a-aa32-0745ff64bb7e.png)

**Comment by sari3l** [comment]
请问什么模式下的呢，地址有选对么

**Comment by sari3l** [comment]
好的，辛苦

**Comment by robinspt** [comment]
早上使用一切正常了，感谢
