### ISSUE TITLE
android 手机的token怎么获取？

### ISSUE THREAD

**Issue by sjtu1011** [sari3l/sams_helper#25]
大佬，我用的华为手机，token怎么获取？网上看到多是IOS系统的介绍，好像说是安卓系统不接受charles的证书

**Comment by ryokoberryz** [comment]
httpcanary

不过我是root的，不root不知能不能抓

**Comment by sari3l** [comment]
不需要 root 也可以，终归是安装一个系统根证书允许获取解密后的内容

工具：HttpCanary、Fiddler等常见的工具都可以

Fiddler 教程：https://www.jianshu.com/p/ec5c786f6326

**Comment by yangying913** [comment]
你好，我mac电脑直接执行可执行文件会直接终端闪退？什么打开方式不对吗？

**Comment by sjtu1011** [comment]
> 

谢谢，搞定啦，后来还是用IOS的手机获取的token，安卓不root还是不行，另外，问一下你碰过到过提示被管理员限制的消息吗？今天试了一下，开始都正常，后面提示被管理员限制了，就看不到可选送货时间了。

**Comment by sari3l** [comment]
> 谢谢，搞定啦，后来还是用IOS的手机获取的token，安卓不root还是不行，另外，问一下你碰过到过提示被管理员限制的消息吗？今天试了一下，开始都正常，后面提示被管理员限制了，就看不到可选送货时间了。

这个问题 #34 #38 均有提到，主要之前版本频率太高，在山姆调整策略后会被拦截，建议换成新版，默认时间为 1s，且支持自定义休眠时间

**Comment by sjtu1011** [comment]
谢谢你的回复！
