### ISSUE TITLE
抢单怎么自动使用优惠券

### ISSUE THREAD

**Issue by liubola** [sari3l/sams_helper#28]
今天发现自动抢到的单子不会使用优惠券。
极速达
暴力运力
沃尔玛卡支付

**Comment by sari3l** [comment]
之前受商品存货波动比较大，使用优惠券可能导致无法正常提交订单（具体逻辑没测试）
另：若想使用优惠券，可见此项目：https://github.com/robGoods/sams

**Comment by sari3l** [comment]
已经在写了，预计下午发布，还是不上线从代码运行，等看下反馈
