### ISSUE TITLE
MacBook如何运行release里面的sams_helper呢？最近刚换的电脑，还不熟悉，像win一样用命令行吗？多谢

### ISSUE THREAD

**Issue by BlueShit-1120** [sari3l/sams_helper#29]

**Comment by sari3l** [comment]
均是使用命令行启动，osx初次运行后需要在“安全性与隐私”中给予信任

关于后者，可见：https://support.apple.com/zh-cn/HT202491

**Comment by BlueShit-1120** [comment]
> 均是使用命令行启动，osx初次运行后需要在“安全性与隐私”中给予信任
> 
> 关于后者，可见：https://support.apple.com/zh-cn/HT202491 `如果您想要打开尚未经过公证或由身份不明的开发者开发的 App` 一节

谢谢您的及时回复，但是命令行运行还是有问题。
![1650940393(1)](https://user-images.githubusercontent.com/54091378/165208065-932d861e-3dce-4c27-a750-0f90b311b4e6.png)
求教，多谢。

**Comment by BlueShit-1120** [comment]
> 均是使用命令行启动，osx初次运行后需要在“安全性与隐私”中给予信任
> 
> 关于后者，可见：https://support.apple.com/zh-cn/HT202491 `如果您想要打开尚未经过公证或由身份不明的开发者开发的 App` 一节

我直接运行的话，会提示没有config这个文件，但我已经复制了啊，是不是权限之类的问题呢
![1650940640(1)](https://user-images.githubusercontent.com/54091378/165208591-9a6653bd-c832-426f-b561-c8431139f20c.png)

**Comment by sari3l** [comment]
需要cd到执行文件目录

**Comment by BlueShit-1120** [comment]
> 需要cd到执行文件目录

谢谢您的回复和帮助。我前面试了cd到目录的，提示command not found
![image](https://user-images.githubusercontent.com/54091378/165216894-38cdd642-a999-4915-b69d-761a321f02a6.png)
头大。

**Comment by sari3l** [comment]
Mac Intel 版对应 [sams_helper_1.0.6_Darwin_x86_64.tar.gz](https://github.com/sari3l/sams_helper/releases/download/v1.0.6/sams_helper_1.0.6_Darwin_x86_64.tar.gz)
Mac Arm 版对应 [sams_helper_1.0.6_Darwin_arm64.tar.gz](https://github.com/sari3l/sams_helper/releases/download/v1.0.6/sams_helper_1.0.6_Darwin_arm64.tar.gz)

在shell中运行
```shell
cd <文件所在目录>
./sams_helper
```

**Comment by BlueShit-1120** [comment]
> 

哦哦哦，mac是这样的啊，win没有那个./，不好意思，对Mac不熟悉，刚上手，万分感谢，给您加个鸡腿！！！1
