### ISSUE TITLE
sams_helper_1.0.0_Windows_x86_64 打开闪退？

### ISSUE THREAD

**Issue by qaz1993930** [sari3l/sams_helper#3]

**Comment by sari3l** [comment]
请在windows 命令行中使用

1. win+R 输入 cmd.exe
2. 从地址栏复制文件所在路径，在cmd.exe中输入 `cd <路径>` 并回车
  例如`C:\Users\sariel.d>cd C:\Users\sariel.d\Desktop\sams_helper_1.0.0_Windows_x86_64`
3. 输入`sams_helper.exe`并回车


```shell
C:\Users\sariel.d>cd C:\Users\sariel.d\Desktop\sams_helper_1.0.0_Windows_x86_64
C:\Users\sariel.d\Desktop\sams_helper_1.0.0_Windows_x86_64>sams_helper.exe
```

**Comment by qaz1993930** [comment]
通过cmd可以打开，谢谢
