### ISSUE TITLE
保供套餐下单逻辑问题

### ISSUE THREAD

**Issue by Mason-star** [sari3l/sams_helper#30]
最近发现保供下单成功率，偏低，发现购物车中会被加入很多保供商品，却无法下单。程序从“发现保供，添加到购物车“-”获取购物车信息”后又跳回去监测保供商品，而非进入抢单

**Comment by Mason-star** [comment]
发现每次这种情况，都是“获取购物信息”后未print任何信息，就继续监测保供，猜测应该是没能正确获取商品信息

**Comment by Mason-star** [comment]
还发现有种情况，保供可以加入到购物车，结算的时候却显示，不支持此配送地区

**Comment by sari3l** [comment]
保供下单是有些复杂的逻辑
1. 保供产品对整个上海，首先监控更新、数量
2. 加入购物车后，才进入到商品逻辑，会检测当前街道是否支持配送，此步骤可能显示“商品无效”，即实际不支持从此地址购买
3. 进入结算环节，受最终策略影响（运力、货源）可能导致无法下单
4. 山姆额外有说明每个保供仅能下单一次，如果取消当天应该没法再购买同一套餐

**Comment by Mason-star** [comment]
确认了一下，出现这种问题的原因，应该是商品可以加入购物车，但在购物车中显示无法配送，可能是山姆按地区投放的原因

**Comment by sari3l** [comment]
OK
