### ISSUE TITLE
运行的时候出现缺少依赖包，请问楼主这个该如何本地导入，go小白，拜谢大佬

### ISSUE THREAD

**Issue by maybeqwe** [sari3l/sams_helper#31]
go: downloading gopkg.in/yaml.v2 v2.4.0
conf\setting.go:4:2: gopkg.in/yaml.v2@v2.4.0: Get "https://proxy.golang.org/gopkg.in/yaml.v2/@v/v2.4.0.zip": dial tcp 142.251.42.241:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by sari3l** [comment]
看样子是没有连接到，可以用国内源替换，可参考：https://learnku.com/go/wikis/38122

**Comment by maybeqwe** [comment]
> 看样子是没有连接到，可以用国内源替换，可参考：https://learnku.com/go/wikis/38122

谢谢大佬，问题已经解决，是一直挂着脚本跑等捡漏吗？一般山姆什么时候释放运力呀？

**Comment by sari3l** [comment]
现在有些迷，一般商品一般是21点，保供我看都说是早晨抢到的，有的套餐也是临时出来的，建议可以一直挂着
