### ISSUE TITLE
终于成功了，但我可以反馈一下问题吗

### ISSUE THREAD

**Issue by JONREAN2** [sari3l/sams_helper#32]
这个抢保供有时候会卡住不停放购物车，显示购物车无效啥的

有时候会卡住，结算不了。

**Comment by twthblzhm** [comment]
是的，确实有这个问题

**Comment by sari3l** [comment]
谢谢反馈，这个问题在于保供套餐有的地方无法购买，之前的逻辑是有些问题

最新的 commit 7712d5c9c790418f6623bba30a2afa124fe3b44e 通过双线程理论上能避免这个问题

但由于`优惠券`和`购买`逻辑均有所改变，暂时只支持`源代码`运行，待反馈后上线
