### ISSUE TITLE
最近几天总出现提交购物车失败的问题

### ISSUE THREAD

**Issue by Frully** [sari3l/sams_helper#35]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/1008448/165438904-ca8fa8c2-e919-449d-b9d7-fb6209540f9a.png">

**Comment by sari3l** [comment]
这个主要是因为有的地方不配送，保供页面是面向上海的，但根据实际地址可能无法购买

**Comment by Frully** [comment]
保供页面展示的商品是根据地址显示的，应该不是这个问题。
据我观察，保供页面刷到商品的时候，商品貌似还不可用，要过很长时间才会变为可用，可能是山姆的缓存问题。
而且出现这个问题后，程序会自动退出，建议增加重试机制。

**Comment by sari3l** [comment]
已清楚问题所在，会退出流程是因为改流程之后有的异常没有捕获

**Comment by sari3l** [comment]
> 并不是，保供页面切换不同收货地址展示的商品是不一样的，目前我知道三个仓库：
> 
> * 上海浦东店
> * 上海青浦店
> * 上海外高桥店
> 
> 可以尝试添加不同地址测试，如松江对应青浦店，徐汇对应浦东店，浦东俱进路对应外高桥店

OK，太难了。。

**Comment by sari3l** [comment]
已更新，请尝试使用最新版，如有问题重启此issue
