### ISSUE TITLE
偶尔出现“服务器正忙，请稍后再试”后会直接退出程序

### ISSUE THREAD

**Issue by Frully** [sari3l/sams_helper#36]

**Comment by twthblzhm** [comment]
是的，服务器高峰期间频现

**Comment by XobilePidor** [comment]
+1

**Comment by omarven** [comment]
+1

**Comment by sari3l** [comment]
有大概在哪一步终止么

**Comment by sari3l** [comment]
另外请问使用的什么版本

**Comment by Frully** [comment]
6bee9faa928a1214ddd2a1a0b23e944a43d6b36e 这个版本
好像是在购物车异常的情况下终止的比较多

<img width="349" alt="image" src="https://user-images.githubusercontent.com/1008448/165458962-abf00e1b-12be-4bce-95b7-3bd26b1cf83d.png">

**Comment by sari3l** [comment]
版本马上更新，所有未知异常都会捕获进入循环

**Comment by sari3l** [comment]
😂副作用就是如果出现什么问题就需要明确哪一步什么环境了，不然发现不了。。

**Comment by Frully** [comment]
感谢

**Comment by BlueShit-1120** [comment]
> 刚还有一个小BUG，请拉最新的代码

可以帮忙把release版本也更新下吗？代码小白，只会一点python，电脑上没有go，多谢！

**Comment by sari3l** [comment]
> > 刚还有一个小BUG，请拉最新的代码
> 
> 可以帮忙把release版本也更新下吗？代码小白，只会一点python，电脑上没有go，多谢！

已更新
