### ISSUE TITLE
日志如下 是获取购物车哪步出错了吗？一直循环这样 然后手动发现购物车被加购了几百件

### ISSUE THREAD

**Issue by heweizhen0822** [sari3l/sams_helper#37]
[>] 发现可购保供商品: 非食套餐, 即将自动添加并下单
########## 获取就近商店信息 ###########
[0] Id：9991 名称：全球购美国直邮, 类型 ：32
[1] Id：4807 名称：上海浦东店, 类型 ：2
[2] Id：9996 名称：山姆全球购保税宁波店, 类型 ：8
########## 获取保供商品【11:44:06】 ###########
[0] 非食套餐 数量：186 单价：0.0 详情：套餐内容:善存小佳维咀嚼片312g+宇津桃叶精华露 200ml*2+MM酒精卫生湿巾 6包*80片+儿童卫生口罩 50枚+艾惟诺婴儿洗发沐浴露 354ml*2+维达抽取式纸面巾 18包*150抽+好奇婴儿湿巾 80抽*6包
[>] 发现可购保供商品: 非食套餐, 即将自动添加并下单
########## 获取就近商店信息 ###########
[0] Id：9991 名称：全球购美国直邮, 类型 ：32
[1] Id：4807 名称：上海浦东店, 类型 ：2
[2] Id：9996 名称：山姆全球购保税宁波店, 类型 ：8
########## 获取保供商品【11:44:07】 ###########
[0] 非食套餐 数量：186 单价：0.0 详情：套餐内容:善存小佳维咀嚼片312g+宇津桃叶精华露 200ml*2+MM酒精卫生湿巾 6包*80片+儿童卫生口罩 50枚+艾惟诺婴儿洗发沐浴露 354ml*2+维达抽取式纸面巾 18包*150抽+好奇婴儿湿巾 80抽*6包
[>] 发现可购保供商品: 非食套餐, 即将自动添加并下单

**Comment by sari3l** [comment]
购物车加了无法下单么？

**Comment by heweizhen0822** [comment]
> 

我用的老版本 是可购买的 主要是这个日志有点诡异 获取购物车有效商品后 即使商品无效按照你的代码日志也会输出购物车金额为0，但是这个没输出直接进入了下一次循环看起来

**Comment by sari3l** [comment]
老版本的逻辑有些问题，只要检测到第一个有数量的套餐就会添加购物车，但是不能购买又会退回到保供检测，有概率在商品抢购完毕前是个死循环

建议使用新版v1.0.7

**Comment by heweizhen0822** [comment]
> 老版本的逻辑有些问题，只要检测到第一个有数量的套餐就会添加购物车，但是不能购买又会退回到保供检测，有概率在商品抢购完毕前是个死循环
> 
> 建议使用新版v1.0.7，看下还有没有这个问题

我看了好久貌似看到这个问题了。你在代码里面不停的改变RunMode 进入了一个死循环。。。好吧建议go代码少用点label，这样跳来跳去的真的容易死循环

**Comment by sari3l** [comment]
> > 老版本的逻辑有些问题，只要检测到第一个有数量的套餐就会添加购物车，但是不能购买又会退回到保供检测，有概率在商品抢购完毕前是个死循环
> > 建议使用新版v1.0.7，看下还有没有这个问题
> 
> 我看了好久貌似看到这个问题了。你在代码里面不停的改变RunMode 进入了一个死循环。。。好吧建议go代码少用点label，这样跳来跳去的真的容易死循环

刚入门，go是真的用起来不是很爽，修改RunMode当时是临时措施😑

**Comment by heweizhen0822** [comment]
> > > 老版本的逻辑有些问题，只要检测到第一个有数量的套餐就会添加购物车，但是不能购买又会退回到保供检测，有概率在商品抢购完毕前是个死循环
> > > 建议使用新版v1.0.7，看下还有没有这个问题
> > 
> > 
> > 我看了好久貌似看到这个问题了。你在代码里面不停的改变RunMode 进入了一个死循环。。。好吧建议go代码少用点label，这样跳来跳去的真的容易死循环
> 
> 刚入门，go是真的用起来不是很爽，修改RunMode当时是临时措施😑

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/36976201/165678956-443609d1-fed7-4176-b51e-8994332a0181.png">
假如这个 _supplyCheck 一直false的话 那么就进入了死循环 不太清楚这个_supplyCheck是检查的什么 我这边连续两天遇到了这个死循环

**Comment by sari3l** [comment]
这个是老版代码逻辑了，新版已经没有了
RunMode 99 是临时状态，主要是用于购买保供商品
86-88 如果在临时态，且购物车里存在目标保供商品，且有效，就持续尝试购买
103-106 如果在临时态，购物车有效商品里没有了目标保供商品，就切换为保供监控重新监控

**Comment by heweizhen0822** [comment]
嗯  已切换新版本明天再战，

**Comment by sari3l** [comment]
祝抢到
