### ISSUE TITLE
存在多个保供包的情况下，下完一个程序会自动终止

### ISSUE THREAD

**Issue by omarven** [sari3l/sams_helper#39]
很大概率就抢到了没啥用的日用洗护类
能一直跑吗？

**Comment by sari3l** [comment]
建议这种配合白名单，因为程序不会判定已购买过得套餐，存在重复下单的可能

**Comment by omarven** [comment]
比如外高桥和青浦都有多个鲜食套餐，不能加个counter吗，对每个item计数？

**Comment by sari3l** [comment]
之前有考虑过全局计数器，唯一的要求就是一直开着，会有这么大的需求么...

**Comment by omarven** [comment]
永远不要低估PM的requirement

**Comment by sari3l** [comment]
> 永远不要低估PM的requirement

🤣

**Comment by sari3l** [comment]
6a96d734cf0f39d88c7703fdc41ffdc5ea00e7c9 已添加
1. `config.yaml - runUnlimited` 开启情况下不会退出程序
2. 已添加`保供抢购`模式下全局购买记录

**Comment by omarven** [comment]
哈哈哈 感觉跟我想的不太一样 
想有个变量itemAmount，对应goods.Index，从0开始计数，每下单一次记1，直到达到设定的itemAmount
