### ISSUE TITLE
how to get sam token？

### ISSUE THREAD

**Issue by yanbinc** [sari3l/sams_helper#4]
how to get sam token？

**Comment by sari3l** [comment]
By use SSL packet capture. The token is in the HTTP Headers with "auth-token" key.

**Comment by GyllLiu** [comment]
you can use Charles to catch the auth-token

**Comment by huzisir** [comment]
运行sams_helper.exe会提示no required module provides package sams_helper.exe: go.mod file not found in current directory or any parent directory; see 'go help modules'这是去哪儿下载，压缩包里没这个文件

**Comment by sari3l** [comment]
> 运行sams_helper.exe会提示no required module provides package sams_helper.exe: go.mod file not found in current directory or any parent directory; see 'go help modules'这是去哪儿下载，压缩包里没这个文件

请问用的windows哪个版本

**Comment by huzisir** [comment]
> > 运行sams_helper.exe会提示no required module provides package sams_helper.exe: go.mod file not found in current directory or any parent directory; see 'go help modules'这是去哪儿下载，压缩包里没这个文件
> 
> 请问用的windows哪个版本

win10专业版 19043.1645

**Comment by sari3l** [comment]
> > > 运行sams_helper.exe会提示no required module provides package sams_helper.exe: go.mod file not found in current directory or any parent directory; see 'go help modules'这是去哪儿下载，压缩包里没这个文件
> > 
> > 
> > 请问用的windows哪个版本
> 
> win10专业版 19043.1645

从release下载的哪个版本呢，我测试x86_64没有出现这个问题
