### ISSUE TITLE
推送可以多点渠道吗

### ISSUE THREAD

**Issue by xsser** [sari3l/sams_helper#40]
微信酱能加点参数吗
加上微信酱的channel 参数
因为现在很多推送好像有问题

**Comment by sari3l** [comment]
> 微信酱能加点参数吗 加上微信酱的channel 参数 因为现在很多推送好像有问题


微信酱的 channel 可以在页面指定呢，这里是避免小白设置

> 动态指定本次推送使用的消息通道，选填。如不指定，则使用网站上的消息通道页面设置的通道

https://sct.ftqq.com/forward

**Comment by sari3l** [comment]
eedc0186546d340984dcc7eaa44f0315dbdfffd1 已更新
