### ISSUE TITLE
开始不显示购物车，且无配送时间列表

### ISSUE THREAD

**Issue by liubola** [sari3l/sams_helper#41]
![image](https://user-images.githubusercontent.com/22904295/165871105-9706be58-77d1-4e0b-8b80-59e898ca4814.png)
早上8点半的时候还能获取购物车，现在就这情况，感觉是不是后台策略更改了，或者其实根本没运力。。

**Comment by meviyysss** [comment]
同样  刷新不到购物车内容  无配送时间  但是切换到外地地址 无购物车内容 依旧可下单

**Comment by liubola** [comment]
> 同样 刷新不到购物车内容 无配送时间 但是切换到外地地址 无购物车内容 依旧可下单

切换至外地，虽然不显示物品，但最后物品还是下单成功了吗

**Comment by liubola** [comment]
其实我感觉是没运力，以往这个点紧俏的东西都没了。。但是购物车都显示还有库存

**Comment by meviyysss** [comment]
> > 同样 刷新不到购物车内容 无配送时间 但是切换到外地地址 无购物车内容 依旧可下单
> 
> 切换至外地，虽然不显示物品，但最后物品还是下单成功了吗

成功了

**Comment by liubola** [comment]
> > > 同样 刷新不到购物车内容 无配送时间 但是切换到外地地址 无购物车内容 依旧可下单
> > 
> > 
> > 切换至外地，虽然不显示物品，但最后物品还是下单成功了吗
> 
> 成功了

外地有配送时间吗？

**Comment by sari3l** [comment]
请问是`保供抢购`模式么？保供默认平时不显示购物车信息，只要检测商品有效就会尝试下单

**Comment by meviyysss** [comment]
> 

极速达也没有

**Comment by meviyysss** [comment]
<img width="488" alt="截屏2022-04-29 上午9 49 45" src="https://user-images.githubusercontent.com/103988517/165873636-7ea90cd8-c667-423b-a5e5-809666f9b8bb.png">

**Comment by liubola** [comment]
> 请问是`保供抢购`模式么？保供默认平时不显示购物车信息，只要检测商品有效就会尝试下单

runMode: 1 抢购模式

**Comment by meviyysss** [comment]
好像是默认不显示了，又可利用的时间才会显示，不知是什么情况。

**Comment by sari3l** [comment]
普陀今天全是极速达，`deliveryType: 2`是全城配

**Comment by sari3l** [comment]
fc9f9902b077ade01bdb2725051b695b26279a52 已修复，同时更新至 v1.0.9

**Comment by liubola** [comment]
感恩，今天山姆普陀好太监，有东西没运力
