### ISSUE TITLE
保供套餐

### ISSUE THREAD

**Issue by maybeqwe** [sari3l/sams_helper#42]
########## 获取当前可用配送时间【11:51:29】 ###########
爆破配送时间范围：2022-04-30 09:00:00 AM - 2022-04-30 09:00:00 PM
[>] 准备爆破提交可配送时段
[!] 请求错误 参数格式错误
########## 提交订单中【11:51:29】 ###########
[!] 请求异常
########## 获取当前可用配送时间【11:51:29】 ###########
爆破配送时间范围：2022-04-30 09:00:00 AM - 2022-04-30 09:00:00 PM
[>] 准备爆破提交可配送时段
[!] 请求错误 参数格式错误
########## 提交订单中【11:51:29】 ###########
[!] 请求异常
########## 获取当前可用配送时间【11:51:29】 ###########
爆破配送时间范围：2022-04-30 09:00:00 AM - 2022-04-30 09:00:00 PM
[>] 准备爆破提交可配送时段
[!] 请求错误 参数格式错误
########## 提交订单中【11:51:29】 ###########
[!] 请求异常
########## 获取当前可用配送时间【11:51:29】 ###########
爆破配送时间范围：2022-04-30 09:00:00 AM - 2022-04-30 09:00:00 PM
[>] 准备爆破提交可配送时段
[!] 请求错误 参数格式错误
########## 提交订单中【11:51:30】 ###########
[!] 请求异常

请问抢保供出现这个问题是正常的吗？

**Comment by sari3l** [comment]
请问哪个版本呢，我检查一下

**Comment by maybeqwe** [comment]
> 请问哪个版本呢，我检查一下 参数格式错误这个很奇怪，方便贴下你的配置么

好像是优惠券的问题，不选优惠券就没事

**Comment by sari3l** [comment]
> > 请问哪个版本呢，我检查一下 参数格式错误这个很奇怪，方便贴下你的配置么
> 
> 好像是优惠券的问题，不选优惠券就没事

😭因为我没有优惠券，所以就很尴尬，不能测试

**Comment by sari3l** [comment]
正常抢购使用优惠券会有问题么？

**Comment by maybeqwe** [comment]
> > > 请问哪个版本呢，我检查一下 参数格式错误这个很奇怪，方便贴下你的配置么
> > 
> > 
> > 好像是优惠券的问题，不选优惠券就没事
> 
> 😭因为我没有优惠券，所以就很尴尬，不能测试

感谢大佬啦，抢到了一但保供，虽然这个保供套餐不太行 555

**Comment by sari3l** [comment]
> > > > 请问哪个版本呢，我检查一下 参数格式错误这个很奇怪，方便贴下你的配置么
> > > 
> > > 
> > > 好像是优惠券的问题，不选优惠券就没事
> > 
> > 
> > 😭因为我没有优惠券，所以就很尴尬，不能测试
> 
> 感谢大佬啦，抢到了一但保供，虽然这个保供套餐不太行 555

加油，应该快了

**Comment by maybeqwe** [comment]
> > > > > 请问哪个版本呢，我检查一下 参数格式错误这个很奇怪，方便贴下你的配置么
> > > > 
> > > > 
> > > > 好像是优惠券的问题，不选优惠券就没事
> > > 
> > > 
> > > 😭因为我没有优惠券，所以就很尴尬，不能测试
> > 
> > 
> > 感谢大佬啦，抢到了一但保供，虽然这个保供套餐不太行 555
> 
> 加油，应该快了

请问这个极速达是不是很难抢呀？只能挂机捡漏嘛，大佬您知道山姆什么时候放运力吗？

**Comment by sari3l** [comment]
> > > > > > 请问哪个版本呢，我检查一下 参数格式错误这个很奇怪，方便贴下你的配置么
> > > > > 
> > > > > 
> > > > > 好像是优惠券的问题，不选优惠券就没事
> > > > 
> > > > 
> > > > 😭因为我没有优惠券，所以就很尴尬，不能测试
> > > 
> > > 
> > > 感谢大佬啦，抢到了一但保供，虽然这个保供套餐不太行 555
> > 
> > 
> > 加油，应该快了
> 
> 请问这个极速达是不是很难抢呀？只能挂机捡漏嘛，大佬您知道山姆什么时候放运力吗？

目前了解到的，一般集中释放是在早 9 点，晚 9 点，两个各自前后半小时

**Comment by 51033044** [comment]
> > > > 请问哪个版本呢，我检查一下 参数格式错误这个很奇怪，方便贴下你的配置么
> > > 
> > > 
> > > 好像是优惠券的问题，不选优惠券就没事
> > 
> > 
> > 😭因为我没有优惠券，所以就很尴尬，不能测试
> 
> 感谢大佬啦，抢到了一但保供，虽然这个保供套餐不太行 555

恭喜恭喜，请问你是那个区域，我在宝山咋没有抢到

**Comment by shengkm** [comment]
保供AddCartGoodsInfo加入购物车后好像没有自动提交订单的后续步骤，是这样的吗？
