### ISSUE TITLE
你好  极速达订单抢购怎么设置呢  

### ISSUE THREAD

**Issue by dupan123** [sari3l/sams_helper#43]

**Comment by sari3l** [comment]
在`config.yaml`中设置以下内容即可
```yaml
runMode: 1
deliveryType: 1
```

**Comment by j5land** [comment]
请教下怎么区分抢购模式 和 捡漏模式？ @sari3l

**Comment by sari3l** [comment]
> 请教下怎么区分抢购模式 和 捡漏模式？ @sari3l

实际没有差别，因为山姆习惯在一些时间点统一发放运力，这个时间就成了抢购；而有些时候有人退单或者临时运力放出，就成了捡漏

对于程序而言
- 程序特定时间运行
- 程序一直运行

**Comment by j5land** [comment]
好的，了解。
