### ISSUE TITLE
请问最新的版本不显示配送时间吗？谢谢！

### ISSUE THREAD

**Issue by 51033044** [sari3l/sams_helper#44]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/47241599/165899623-2befe3e5-316a-41bd-983e-f284ba038521.png">

**Comment by sari3l** [comment]
请问是最新版v1.1.0出现的问题么

**Comment by sari3l** [comment]
目前没有运力是不会显示的

**Comment by sari3l** [comment]
v1.1.0已更新，请重新下载使用
