### ISSUE TITLE
运力时间显示问题

### ISSUE THREAD

**Issue by Mason-star** [sari3l/sams_helper#45]
########## 获取当前可用配送时间【16:24:27】 ###########
配送时间： 2022/04/29 周五 16:00 - 19:00, 是否可用：false
当前无可用配送时间段
这是之前版本，现在不显示"配送时间： 2022/04/29 周五 16:00 - 19:00, 是否可用：false"，是bug么

**Comment by sari3l** [comment]
最新的 v1.1.0 应该已经解决了这个问题

**Comment by sari3l** [comment]
v1.1.1 已修正所有模式下均完整显示运力列表
