### ISSUE TITLE
获取履约配送信息异常

### ISSUE THREAD

**Issue by IceCd1996** [sari3l/sams_helper#46]
具体情况是：程序显示有可用时间段运力，但是提交订单时提示“获取履约配送信息异常”。查看app中显示“今日运力繁忙，全城配无法配送”。
想问一下这是什么情况？

**Comment by sari3l** [comment]
如果开启了`运力爆破`，在没有运力的情况下也会尝试强制提交，建议挂机情况可关闭

```yaml
bruteCapacity: true
```

**Comment by IceCd1996** [comment]
感谢大佬

> 如果开启了`运力爆破`，在没有运力的情况下也会尝试强制提交，建议挂机情况可关闭
> 
> ```yaml
> bruteCapacity: false
> ```

感谢大佬

**Comment by sari3l** [comment]
> > 感谢大佬
> > > 如果开启了`运力爆破`，在没有运力的情况下也会尝试强制提交，建议挂机情况可关闭
> > > ```yaml
> > > bruteCapacity: false
> > > ```
> > 
> > 
> > 感谢大佬
> 
> > 如果开启了`运力爆破`，在没有运力的情况下也会尝试强制提交，建议挂机情况可关闭
> > ```yaml
> > bruteCapacity: false
> > ```
> 
> 尝试过修改关闭运力爆破模式，仍然出现获取履约配送信息异常的情况。 怀疑是配送时间的问题所以凌晨又试了一下，app上配送时间可用，可以下单支付购买，但是程序中还是不行，求解。

最新版已经重新显示所有已获取的运力列表，可以对照看一下，另外可能也跟购物车商品类型有关，尚不清楚为何触发
