### ISSUE TITLE
你好 购物车内有货品后抢购出现一下信息 请问是怎么回事 谢谢

### ISSUE THREAD

**Issue by street83** [sari3l/sams_helper#50]
[!] [403] <!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AccessDeny</title><link rel="stylesheet" href="https://imgcache.qq.com/qcloud/security/static/404style.css"></head><body><div class="conent"><div class="accessDenySvg"><img src="https://imgcache.qq.com/qcloud/security/static/imgs/attackIntercept.svg" alt=""></div><h1 class="err">很抱歉，您提交的请求可能对网站造成威胁，请求已被管理员设 置的策略阻断</h1><p class="text1">本页面为<span class="text-color">腾讯T-Sec Web应用防火墙(WAF)</span>默认提示页面，如有疑问请联系网站管理员并提供UUID信息</p><p class="text2">您的请求UUID为：<span class="text2-id">b248e91f1b6fd19874d84d2de40f1edf-ca853d78c0c180193eebfe038212142a</span> <span id="copy"><img src="https://imgcache.qq.com/qcloud/security/static/imgs/copy.svg" alt=""> <span class="tooltips">复制成功</span></span></p></div></body><script>var copyBtn=document.getElementById("copy"),id=document.querySelector(".text2-id");copyBtn.addEventListener("click",function(){var e=id.innerHTML,t=document.createElement("input");t.value=e,document.body.appendChild(t),t.select(),document.execCommand("Copy"),document.body.removeChild(t),document.querySelector(".tooltips").style.display="block";setTimeout(function(){document.querySelector(".tooltips").style.display="none"},2e3)})</script></html>

**Comment by sari3l** [comment]
访问太频繁被拦击了，#34 也是同样的问题，现在的建议`bruteCapacity: false`，且非必要不要长时间运行

**Comment by street83** [comment]
好的谢谢！
