### ISSUE TITLE
问下怎么操作可以把没货的商品提前加入购物车

### ISSUE THREAD

**Issue by meviyysss** [sari3l/sams_helper#51]
感恩

**Comment by 51033044** [comment]
这个想法特别好，特别希望加上，感恩

**Comment by liubola** [comment]
爬下已经closed的issues 有解决方案

**Comment by Frully** [comment]
> 爬下已经closed的issues 有解决方案

解决方案是指用关键词增加多个商品么？

**Comment by liubola** [comment]
> > 爬下已经closed的issues 有解决方案
> 
> 解决方案是指用关键词增加多个商品么？

https://github.com/sari3l/sams_helper/issues/20#issuecomment-1107684793

**Comment by sari3l** [comment]
后面计划加一个开关，所有物品不管数量直接添加

**Comment by sari3l** [comment]
已更新，稍后修复 #53 后统一打包

**Comment by sari3l** [comment]
`addForce: true`无货保供商品会提前加入购物车（受黑白名单设置影响）
