### ISSUE TITLE
早上8点运行一直购物车无有效商品

### ISSUE THREAD

**Issue by j5land** [sari3l/sams_helper#52]
如题。
等到8点半，重新运行程序，就能查询到商品了。
但这样错过了抢购最佳时间。
请问大家有没有出现这种类似情况？
程序自动运行一直查询购物车无有效商品，程序重新运行是能查询到的。

下图是第二次运行能查询到商品，但是错过了配送被抢完了。
![20220501083259](https://user-images.githubusercontent.com/1421509/166127225-5a6a1a3b-40d7-40cd-b382-bf2bb5b4f7f5.jpg)

**Comment by Mason-star** [comment]
有，我真正想提这个issue，再放货前后，显示购物车无有效商品订单金额0，放货后仍然是无有效商品，此时实际购物车是存在有效商品，重启一次软件，便显示了，算个小bug

**Comment by j5land** [comment]
嗯，想到了。
这个是一个特殊场景：
1. 门店没开放，比如：上海普陀DC店，并不是一直开着的。
2. 所以第一次运行无法查询到门店信息；
3. CheckCart 的时候没有这家门店信息，没有这家门店信息；
4. 再次运行，门店已上线，就能查询到对应购物车商品信息了；

所以，我认为CheckCart 要与 GetStoreList 联动。

**Comment by j5land** [comment]
代码修改好了

**Comment by liubola** [comment]
> 代码修改好了

enhanced一个啊，我也是普陀dc，你这咋不显示运力

**Comment by sari3l** [comment]
> 嗯，想到了。 这个是一个特殊场景：
> 
> 1. 门店没开放，比如：上海普陀DC店，并不是一直开着的。
> 2. 所以第一次运行无法查询到门店信息；
> 3. CheckCart 的时候没有这家门店信息，没有这家门店信息；
> 4. 再次运行，门店已上线，就能查询到对应购物车商品信息了；
> 
> 所以，我认为CheckCart 要与 GetStoreList 联动。

之前没遇到过这种情况，那么所有checkCart都要返回到getStoreList，我检查一下

**Comment by sari3l** [comment]
已更新代码，待解决保供列表问题统一打包

**Comment by sari3l** [comment]
v1.1.2 `updateStoreForce: true` 请求购物车信息时会强制刷新商店信息，防范某些店突然开门
由于此问题发生于早晨开店，同时因不确定影响范围，暂定默认`false`
