### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by meviyysss** [sari3l/sams_helper#53]
![WechatIMG2081](https://user-images.githubusercontent.com/103988517/166130261-26cc06b0-3f4f-4c47-a2a4-9ca51531034a.jpeg)

提取保供商品 提不到下拉商品的东西

**Comment by sari3l** [comment]
页面更新了，我稍后看一下

**Comment by sari3l** [comment]
为啥我的页面就几样东西。。。

**Comment by meviyysss** [comment]
> 页面更新了，暂时我这边还是只有三件商品，请问大概抢购的时间点和位置么，我复现一下

现在又没了变了 中午12点的时候有

**Comment by sari3l** [comment]
> > 页面更新了，暂时我这边还是只有三件商品，请问大概抢购的时间点和位置么，我复现一下
> 
> 现在又没了变了 中午12点的时候有

请问是在哪个区，我先定位过去

**Comment by meviyysss** [comment]
> > > 页面更新了，暂时我这边还是只有三件商品，请问大概抢购的时间点和位置么，我复现一下
> > 
> > 
> > 现在又没了变了 中午12点的时候有
> 
> 请问是在哪个区，我先定位过去

浦东 都有

**Comment by sari3l** [comment]
我目前只能先挂着看下数据包了

**Comment by meviyysss** [comment]
发现中午的单品 现在全城配都有货  但还没有运力

**Comment by sari3l** [comment]
暂时还没看到更多商品按钮，待观察

**Comment by meviyysss** [comment]
> 暂时还没看到更多商品按钮，待观察

现在页面有商品了

**Comment by sari3l** [comment]
> > 暂时还没看到更多商品按钮，待观察
> 
> 现在页面有商品了

一直没能刷到那个按钮出现，方便丢一下数据包么

**Comment by meviyysss** [comment]
> > > 暂时还没看到更多商品按钮，待观察
> > 
> > 
> > 现在页面有商品了
> 
> 一直没能刷到那个按钮出现，方便丢一下数据包么

嗯 还没有按钮 只有几个商品
