### ISSUE TITLE
浦东店现在有很多保供单品，但是程序只能获取到第一页的商品，“更多列表”里面的获取不到

### ISSUE THREAD

**Issue by Frully** [sari3l/sams_helper#54]
![点击更多前](https://user-images.githubusercontent.com/1008448/166130204-0b7ff8a2-4f0f-41b6-9c1a-dddcfaee276f.png)
点击更多前

![点击更多后](https://user-images.githubusercontent.com/1008448/166130215-acdb743d-8430-48b7-8178-188da9ab75cc.png)
点击更多后

**Comment by sari3l** [comment]
同 #53，后续跟进在那边，故关闭此issue
