### ISSUE TITLE
# 更新购物车前强制更新商店信息 updateStoreForce: true 后会意外终止

### ISSUE THREAD

**Issue by ituren** [sari3l/sams_helper#57]
`➜  sams_helper git:(main) ✗ go run main.go
########## 选择支付方式 ##########
选择说明：
[0] 微信
[1] 支付宝
[2] 银联
[3] 沃尔玛礼品卡

[>] 请输入序号（0, 1, 2...)：
0
[>] 已选支付方式：微信
########## 切换购物车收货地址 ##########
[0] 黄 宝山区 
[1] 杨 虹口区 
[2] 陆 浦东新区 
[3] 郑 浦东新区
[4] 郑 浦东新区

[>] 请输入序号（0, 1, 2...)：
3
[>] 已选地址：郑 浦东新区 
########## 选择使用优惠券 ##########
[!] 没有查询到有效的优惠券，跳过此步骤
########## 更新就近商店信息【09:09:38】 ###########
[0] Id：9991 名称：全球购美国直邮, 类型 ：32
[1] Id：6988 名称：上海外高桥山姆, 类型 ：2
[2] Id：6683 名称：金桥DC, 类型 ：4
[3] Id：9996 名称：山姆全球购保税宁波店, 类型 ：8
########## 获取购物车中有效商品【09:09:38】 ###########
[0] 带排猪方肉 2.1kg 数量：2 单价：121.40
[1] MM 精选鲜鸡蛋 30枚 数量：1 单价：23.80
[2] MM&湾仔码头 玉米蔬菜猪肉水饺1.98kg 数量：1 单价：55.90
[>] 订单总价：322.50
########## 获取当前可用配送时间【09:09:39】 ###########
配送时间： 2022/05/02 周一 11:30 - 14:30, 是否可用：false
[!] 当前无剩余运力，重新检测是否释放
########## 获取当前可用配送时间【09:09:40】 ###########
配送时间： 2022/05/02 周一 11:30 - 14:30, 是否可用：false
[!] 当前无剩余运力，重新检测是否释放
########## 获取当前可用配送时间【09:09:41】 ###########
配送时间： 2022/05/02 周一 11:30 - 14:30, 是否可用：false
[!] 当前无剩余运力，重新检测是否释放
########## 获取当前可用配送时间【09:09:42】 ###########
配送时间： 2022/05/02 周一 11:30 - 14:30, 是否可用：false
[!] 当前无剩余运力，重新检测是否释放
########## 获取当前可用配送时间【09:09:43】 ###########
配送时间： 2022/05/02 周一 11:30 - 14:30, 是否可用：false
[!] 当前无剩余运力，重新检测是否释放
########## 获取当前可用配送时间【09:09:44】 ###########
配送时间： 2022/05/02 周一 11:30 - 14:30, 是否可用：false
[!] 当前无剩余运力，重新检测是否释放

...

########## 获取当前可用配送时间【09:11:26】 ###########
配送时间： 2022/05/02 周一 11:30 - 14:30, 是否可用：false
[!] 当前无剩余运力，重新检测是否释放
########## 获取购物车中有效商品【09:11:28】 ###########
[0] MM 精选鲜鸡蛋 30枚 数量：1 单价：23.80
[1] MM 进口全脂纯牛奶 1L*6 数量：1 单价：49.90
[2] MM 原味麻薯面包 24个 数量：1 单价：35.80
[3] 奶油西瓜 1颗 数量：1 单价：69.80
[>] 订单总价：109.50
########## 开始校验当前商品【09:11:28】 ###########
[!] 校验商品失败：当前区域不支持配送，请重新选择地址
[!] 当前区域不支持配送，请重新选择地址
➜  sams_helper git:(main) ✗ go run main.go`

猜测是选中的商店突然关闭，打开APP查看，商店又上线了

**Comment by ituren** [comment]
更新下复现步骤：在A店开启脚本后，在APP侧将地址切换到B店区域，然后切换到购物车页面，即可复现。

**Comment by sari3l** [comment]
🤦‍♂️山姆的用户信息是记录地址的，程序跑 A，应用切换 B 肯定是出问题的

**Comment by ituren** [comment]
嗯，想看下亲戚家能买啥就触发bug了

**Comment by sari3l** [comment]
应该是亲戚用的另一个仓导致触发的

**Comment by ituren** [comment]
应该是的
