### ISSUE TITLE
请问关键字是不是只针对 保供产品；如果是的话， 保供产品页面最下面有 精选商品，好像目前版本没有获取，谢谢！

### ISSUE THREAD

**Issue by 51033044** [sari3l/sams_helper#58]

**Comment by sari3l** [comment]
哪个版本？精选商品是 #53 页面里的单品么？现在能获取到呢？

**Comment by 51033044** [comment]
好像不是，具体你看下面截图。 另外可能存在下面两种情况：第一最新商品上线了，我们程序没有及时刷新。第二种情况 就是#53号说的 获取不完全。 版本是今天刚刚下载的源码运行的。谢谢！
![IMG_7782](https://user-images.githubusercontent.com/47241599/166195058-bd58c90e-fab5-430f-8c50-8cb113803839.PNG)

**Comment by sari3l** [comment]
这个应该是单纯的广告推荐，每个人可能不太一样的样子，感觉更倾向于极速达商品

**Comment by 51033044** [comment]
好的，请问普通商品能否使用 关键字？并且可以强制加入 购物车，谢谢！

**Comment by sari3l** [comment]
> 好的，请问普通商品能否使用 关键字？并且可以强制加入 购物车，谢谢！

暂时没有这个功能，因为用起来很奇怪，要人工介入，其实直接写个小脚本就行

**Comment by 51033044** [comment]
> > 好的，请问普通商品能否使用 关键字？并且可以强制加入 购物车，谢谢！
> 
> 暂时没有这个功能，因为用起来很奇怪，要人工介入，其实直接写个小脚本就行
谢谢，也可以不用人工介入，就是 关键字也可以争对普通商品就可以了。

**Comment by sari3l** [comment]
> > > 好的，请问普通商品能否使用 关键字？并且可以强制加入 购物车，谢谢！
> > 
> > 
> > 暂时没有这个功能，因为用起来很奇怪，要人工介入，其实直接写个小脚本就行
> 
> 谢谢，也可以不用人工介入，就是 关键字也可以争对普通商品就可以了。

山姆的搜索是很奇怪的模糊搜索，另外想单独使用SpuId添加也必须配合相应的StoreId，所以暂不考虑，建议自行开发

**Comment by 51033044** [comment]
> > > > 好的，请问普通商品能否使用 关键字？并且可以强制加入 购物车，谢谢！
> > > 
> > > 
> > > 暂时没有这个功能，因为用起来很奇怪，要人工介入，其实直接写个小脚本就行
> > 
> > 
> > 谢谢，也可以不用人工介入，就是 关键字也可以争对普通商品就可以了。
> 
> 山姆的搜索是很奇怪的模糊搜索，另外想单独使用SpuId添加也必须配合相应的StoreId，已更新，但是一般人感觉用不到

感谢，已看到。请问 关键字输入和 保供产品共同？另外 冷加载 和 热加载 区别在哪？

**Comment by 51033044** [comment]
> > > > > 好的，请问普通商品能否使用 关键字？并且可以强制加入 购物车，谢谢！
> > > > 
> > > > 
> > > > 暂时没有这个功能，因为用起来很奇怪，要人工介入，其实直接写个小脚本就行
> > > 
> > > 
> > > 谢谢，也可以不用人工介入，就是 关键字也可以争对普通商品就可以了。
> > 
> > 
> > 山姆的搜索是很奇怪的模糊搜索，另外想单独使用SpuId添加也必须配合相应的StoreId，已更新，但是一般人感觉用不到
> 
> 感谢，已看到。请问 关键字输入和 保供产品共同？另外 冷加载 和 热加载 区别在哪？

请问 关键字输入和 保供产品共同 这个问题解决了，是在goodslist文件夹里添加。谢谢！冷热加载大概我也清楚了。谢谢

**Comment by sari3l** [comment]
关键字面向所有商品，保供是商品的一类
- 冷加载 启动后只加载一次
- 热加载 根据stepGoodsHotModeSleep时间循环加载（只有判断文件修改后才会正式加载）
