### ISSUE TITLE
保供套餐添加到购物车之后，开启抢购物车模式，ip被封了

### ISSUE THREAD

**Issue by maerha17** [sari3l/sams_helper#59]
src="https://imgcache.qq.com/qcloud/security/static/imgs/attackIntercept.svg" alt=""></div><h1 class="err">很抱歉，您提交的请求可能对网站造成 
威胁，请求已被管理员设置的策略阻断</h1><p class="text1">本页面为<span class="text-color">腾讯T-Sec Web应用防火墙(WAF)</span>默认提示页面，如有疑问请联系网站管理员并提供UUID信息</p><p class="text2">

**Comment by sari3l** [comment]
#34 自行调整sleepTimeSet，这个没办法，开时间太久有几率被拦截，大概一个钟或半小时就解封了
