### ISSUE TITLE
你好 为什么一直显示auth-token过期

### ISSUE THREAD

**Issue by street83** [sari3l/sams_helper#6]
你好 为什么一直显示auth-token过期
谢谢

**Comment by sari3l** [comment]
请问是抓取的 64 位的 token 么

**Comment by street83** [comment]
搞定了！谢谢
再问下大概哪个时段成功率比较高些，挂了几个小时暂无成果

**Comment by sari3l** [comment]
建议20:50:00开始等一个小时，因为挂单30分钟会被系统退单，所以有概率21:30左右有一波小运力
另外，部分地区如果运力一直显示是隔天的话，大概率是那个地区不能配送（目前正常运力都安排在一周后）

**Comment by street83** [comment]
好的，谢谢

**Comment by hydra77** [comment]
> 搞定了！谢谢
> 再问下大概哪个时段成功率比较高些，挂了几个小时暂无成果

请问怎么解决的呀，我也是这个问题。

**Comment by sari3l** [comment]
> > 搞定了！谢谢
> > 再问下大概哪个时段成功率比较高些，挂了几个小时暂无成果
> 
> 请问怎么解决的呀，我也是这个问题。

运力太少了，这两天直接宣布改成保供了
