### ISSUE TITLE
GotoCartStep 的sleep好像没有生效

### ISSUE THREAD

**Issue by idkwtl** [sari3l/sams_helper#60]
购物车里没有有效商品时，重试速度非常快，调整stepCartSleep和stepCartShowSleep参数没有效果。

**Comment by sari3l** [comment]
是不是开启了`updateStoreForce`，这样子会导致重复检测，已修正

**Comment by idkwtl** [comment]
> 是不是开启了`updateStoreForce`，这样子会导致重复检测，已修正

对的，开了updateStoreForce。等更新：）

**Comment by sari3l** [comment]
已更新，在打包

**Comment by idkwtl** [comment]
> 已更新 v1.1.4

新版session.GetGuaranteedSupplyGoodsV2报错，改成GetGuaranteedSupplyGoods可以了

**Comment by sari3l** [comment]
？方便贴一下图么

**Comment by sari3l** [comment]
> > 已更新 v1.1.4
> 
> 新版session.GetGuaranteedSupplyGoodsV2报错，改成GetGuaranteedSupplyGoods可以了

？方便贴一下图么，v2是获取保供时“更多商品”的更新

**Comment by idkwtl** [comment]
完整报错是这样的
.\main.go:397:28: session.GetGuaranteedSupplyGoodsV2 undefined (type *sams.Session has no field or method GetGuaranteedSupplyGoodsV2)

然后把397行session.GetGuaranteedSupplyGoodsV2()改成 session.GetGuaranteedSupplyGoods() 可以正常运行

**Comment by sari3l** [comment]
> 完整报错是这样的 .\main.go:397:28: session.GetGuaranteedSupplyGoodsV2 undefined (type *sams.Session has no field or method GetGuaranteedSupplyGoodsV2)
> 
> 然后把397行session.GetGuaranteedSupplyGoodsV2()改成 session.GetGuaranteedSupplyGoods() 可以正常运行

这咋看的像是没更新代码

**Comment by idkwtl** [comment]
是我没更新全量代码，打扰了…………

**Comment by sari3l** [comment]
🤣
