### ISSUE TITLE
请问是否可以添加【超重订单自动分批下单】功能？

### ISSUE THREAD

**Issue by Timemie** [sari3l/sams_helper#66]
住在老小区，帮小区老人抢菜，一般订单重量会超重，能否考虑添加超重订单自动分批下单功能，谢谢

**Comment by sari3l** [comment]
此需求与目前多个功能潜在冲突，处理中

**Comment by Timemie** [comment]
感谢作者！

**Comment by Timemie** [comment]
今天小区分批发了出入证，群里大家都在讨论去山姆购物。
5.1开始帮小区居民代购山姆，截止到5.19，抢购40多单，累计金额大约4.8w左右，微信群人数200人左右。
来给作者还个愿，感谢你的付出让大家在疫情期间买到山姆🙏🙏🙏

附小区分货云表格(已脱敏处理)：
【1-18期】https://docs.qq.com/sheet/DTGlBbWNXbllxTU1L
【19-31期】https://docs.qq.com/sheet/DTEZmWlFnbUpDS1hV
【32-40期】https://docs.qq.com/sheet/DTHNGTndVclF4d0JH
【40-50期】https://docs.qq.com/sheet/DTHVCbkNmVWlmUUhJ

**Comment by sari3l** [comment]
帮到就好
