### ISSUE TITLE
保供监控错误，但小程序和APP都可以获取到保供套餐信息。

### ISSUE THREAD

**Issue by maerha17** [sari3l/sams_helper#68]
########## 获取保供商品【15:29:57】 ###########
[!] 保供监控错误：code: THREAD_ERROR 系统繁忙，请稍后再试

**Comment by maerha17** [comment]
已手动添加购物车后，用山姆抢购模式下单成功。
已成功下了好几单了，非常感谢作者。

**Comment by sari3l** [comment]
> ########## 获取保供商品【15:29:57】 ########### [!] 保供监控错误：code: THREAD_ERROR 系统繁忙，请稍后再试

这个貌似是山姆网络问题，可以尝试将`stepSupplySleep`调大一些
