### ISSUE TITLE
提示：商品已过期

### ISSUE THREAD

**Issue by SLtudou4** [sari3l/sams_helper#7]
![image](https://user-images.githubusercontent.com/17898186/163802192-4760d147-379e-45db-bb04-32e642115918.png)
请教一下一直提示商品已过期如何处理

**Comment by sari3l** [comment]
请通过 APP 或者小程序确认商品有效性呢，如果线上显示商品是有的但是仍有这个问题的话，麻烦请发一下购物车截图

**Comment by SLtudou4** [comment]
![image](https://user-images.githubusercontent.com/17898186/163815007-ebc58d6c-77e3-4167-bc70-6759dcf578fe.png)

token抓的ios的小程序的

**Comment by sari3l** [comment]
麻烦请用一下最新的 v1.0.2，截一下输出，我检查下商品信息，ID 太难找了😭
