### ISSUE TITLE
极速达出现未知失败

### ISSUE THREAD

**Issue by huzisir** [sari3l/sams_helper#72]
![图片](https://user-images.githubusercontent.com/103866646/167243074-5658f009-a400-4b24-a3a0-dbe9f8c93e12.png)

**Comment by sari3l** [comment]
很尴尬，属于完全未知的异常，能贴一下脱敏的config.yaml配置么

**Comment by huzisir** [comment]
没有，而且购物车里有两件商品，但只识别出蜜瓜这一个，早上抢还正常显示运力不足的，下午听人说开放运力了试了一下就这样了
###############################
# 基础设置
###############################
# 山姆会员 Token
authToken: "740d926b981716f426e7559ad74bf050eac6a08b371b0c3a6d88c648fa67e766"
# 运行模式
# 1->山姆抢购 | 2->保供抢购
runMode: 1
# 配送方式
# 1->极速达 | 2->全城配
deliveryType: 1
# 运力暴力模式（仅全城配有效）
bruteCapacity: true
# 更新购物车前强制更新商店信息，早中时间抢购建议开启
updateStoreForce: true
# 全平台购物车勾选状态同步
# 注意：1. 同一件商品，极速达全城配相互切换时，若商品有货则默认勾选
#      2. 其他情景未知
cartSelectedStateSync: true

###############################
# 下单金额限制，非必须不需修改
###############################
moneySet:
  # 单次订单金额下限（元）
  amountMin: 0
  # 单次订单金额上限（元）
  amountMax: 10000
  # 累计金额上限（元）
  totalLimit: 10000

###############################
# 默认配置，一般不需修改
###############################
# 设备类型模拟
# 1->IOS | 2->小程序
deviceType: 1
# 是否忽略无效商品
ignoreInvalid: true
# 商店类型
# 2->生鲜直达 | 4->极速达 | 8->全球购保税
storeType: 4
# 商品类型
# 1->普通商品 | 2->全球购商品
floorId: 1
# 运力搜索时间跨度（日）
perDateLen : 7
# SaasId
saasId: "1818"

###############################
# 通知功能
###############################
# 通知设置
noticeSet:
  # 通知类型
  # 0->不通知 | 1->Bark | 2->Server酱 | 3->OSX 系统语音
  noticeType: 1

  # Bark 通知配置
  bark:
    # Bark 端点地址
    barkServer: "https://api.day.app"
    # Bark Token
    barkToken: "VhXMDis4pBSbWJ7kSBmnWA"
    # 信息内容
    barkMessage: "【山姆助手】抢购成功，请及时付款！"
    # 提示音
    barkSound: "telegraph"

  # Server酱 通知配置
  ftqq:
    # Server酱 端点地址
    ftqqServer: "https://sctapi.ftqq.com"
    # 用户 Token，获取方式：https://sct.ftqq.com/sendkey
    ftqqSendKey: "<ftqqSendKey>"
    # 消息通道：最多支持两通道如："9|66"，具体通道请看 https://sct.ftqq.com/sendkey
    # 默认：方糖服务号
    ftqqChannel: "9"
    # 信息标题
    ftqqTitle: "【山姆助手】提醒"
    # 信息内容
    ftqqDesp: "抢购成功，请及时付款！"

  # OSX 系统语音配置
  sound:
    # 语音信息
    soundMessage: "山姆抢到啦 快去付款"
    # 重复播报次数
    soundTimes: 2
    # 播报声音
    soundVoice: "Ting-ting"

###############################
# 高级功能
###############################
# 永不停歇（下单成功不退出）
runUnlimited: false

# 超重订单自动分批下单（仅极速达有效）
autoShardingForOrder: true

# （精准）自动搜索、强制添加指定商品
# 注：通过此功能无货商品可提前加入购物车
addGoodsFromFileSet:
  # 是否开启
  isEnabled: false
  # 加载方式，冷加载只执行一次，热加载每隔 stepGoodsHotModeSleep 循环执行
  # 1->冷加载 | 2->热加载
  mode: 1
  # 显示商品细节
  showGoodsInfo: true

# 保供抢购关键字黑白名单筛选
supplySet:
  # 不管是否有库存数量，强制添加进购物车
  addForce: false
  # 总是输出购物车信息（不建议开启）
  showCartAlways: false
  # 黑白名单筛选
  parseSet:
    # 是否开启
    isEnabled: false
    # 筛选方式
    # 1->白名单 | 2->黑名单
    mode: 1
    # 检测有以下关键字的内容，例：["蔬菜", "保供套餐C"]
    keyWords: ["<关键字>"]

# 代理设置
proxySet:
  # 是否开启代理
  isEnabled: false
  # 代理 URL
  proxyUrl: "http://127.0.0.1:8080"

# 自动修正限购商品数量
autoFixPurchaseLimit:
  # 是否开启
  isEnabled: true
  # 是否开启线下修正，只影响最后提交订单内容
  fixOffline: true
  # 是否开启线上修正，会影响线上购物车商品的数量
  fixOnline: false

# 自动输入设置
autoInputSet:
  # 是否开启
  isEnabled: false
  # 支付方式序号
  # 0->微信 | 1->支付宝 | 2->银联 | 3->沃尔玛礼品卡
  inputPayMethod: 0
  # 地址序号
  inputAddress: 0
  # 优惠券序号列表，例：[0,1,2]
  inputCouponList: []

# 各步骤休眠时间（毫秒）
sleepTimeSet:
  # 请求商店信息
  stepStoreSleep: 1000
  # 请求购物车信息
  stepCartSleep: 1000
  # 购物车信息展示
  stepCartShowSleep: 1000
  # 检查商品有效性
  stepGoodsSleep: 1000
  # 请求运力信息
  stepCapacitySleep: 1000
  # 下单间隔
  stepOrderSleep: 100
  # 请求保供商品信息
  stepSupplySleep: 1000
  # 热加载睡眠时间
  stepGoodsHotModeSleep: 10000

**Comment by huzisir** [comment]
现在又正常了，很奇怪，估计是山姆那边的问题吧

**Comment by sari3l** [comment]
```yaml
addGoodsFromFileSet:
  # 是否开启
  isEnabled: false
```
应该不会启动商品加载呢？

**Comment by sari3l** [comment]
> 现在又正常了，很奇怪，估计是山姆那边的问题吧

这种情况如果有数据包是最好的，因为直接 FAILED 很少遇到
另外商品加载采用的字符串包含，商品名称越完整越好，同时注意yaml格式
另：这里还有个潜在问题，如果商店在加载商品列表前后是关闭、开启的状态，可能有物品没有加载，但是出现的概率太低了...

**Comment by huzisir** [comment]
大概是另一件商品的原因，安东尼罗德 法国进口 夏布利一级园干白葡萄酒750ml，这个商品参加满6件打9折的优惠，然后只要这个商品加购物车，脚本就识别出未勾选，然后提示未知失败，加其他商品就没事

**Comment by sari3l** [comment]
> 大概是另一件商品的原因，安东尼罗德 法国进口 夏布利一级园干白葡萄酒750ml，这个商品参加满6件打9折的优惠，然后只要这个商品加购物车，脚本就识别出未勾选，然后提示未知失败，加其他商品就没事

我测试下

**Comment by sari3l** [comment]
v1.2.0 已修复

**Comment by Timemie** [comment]
这个今天我也遇到了，购物车有一件满2件打折的商品，勾选下单就会出现未知错误

**Comment by huzisir** [comment]
感谢大佬
