### ISSUE TITLE
########## 初始化用户信息 ########## [!] 鉴权失败 auth-token 过期

### ISSUE THREAD

**Issue by JimmyABZ** [sari3l/sams_helper#73]
这是什么原因呢，大佬

**Comment by JimmyABZ** [comment]
########## 初始化用户信息 ##########
[!] 鉴权失败 auth-token 过期

**Comment by sari3l** [comment]
一般认为登录设备过多或者header有部分参数需要明确，可以自行抓包修改requests.go

**Comment by sari3l** [comment]
...你 token 两边的`<>`删了没

**Comment by JimmyABZ** [comment]
就是没注意<>没删，后来看到了，删了就好了。今天试了下，可以顺利下单，但是选择了优惠卷，最后结账的时候还是没有使用

**Comment by sari3l** [comment]
> 就是没注意<>没删，后来看到了，删了就好了。今天试了下，可以顺利下单，但是选择了优惠卷，最后结账的时候还是没有使用

优惠券使用条件达到了么，应该是会扣除的

**Comment by JimmyABZ** [comment]
今天好像后台加入了防火墙，刷新超过两分钟，就会被ban，有解决办法吗大佬

**Comment by JimmyABZ** [comment]
后台加入了防火墙

**Comment by JimmyABZ** [comment]
今天好像后天新增了防火墙，刷新连续超过2分钟就会被BAN，有方法绕过吗大佬

**Comment by sari3l** [comment]
刷新哪个请求被 BAN 呢，我测试下？
另外 BAN 的是 authtoken，暂时只能等解封

**Comment by JimmyABZ** [comment]
连续刷新运力请求就会被ban，如果调整刷新时间能避免吗，我测试了一下，有时候4分钟会被ban，有时候2分钟会被ban，有时候几十秒就会被Ban

**Comment by sari3l** [comment]
那就是升级策略了，暂时没办法

**Comment by JimmyABZ** [comment]
增加运力刷新请求时间的话，也一定会被ban吗？

**Comment by sari3l** [comment]
这个具体是腾讯云的 WAF 策略，没有足够信息前，任何特征都可能是 BAN 的原因

**Comment by sari3l** [comment]
你用的哪种模式？

**Comment by JimmyABZ** [comment]
模式是指哪个？终端运行？时间本身默认1000毫秒，现在可能过了高峰期了，2点左右的时候就会被很快ban

**Comment by sari3l** [comment]
普通抢购，还是 保供抢购

可能 2 点时候策略比较严，等明天再测试下

**Comment by JimmyABZ** [comment]
普通抢购，就是买下午2点的，早上11点半的保供我没用，所以不知道那个时间段会不会很快被ban

**Comment by JimmyABZ** [comment]
老哥山姆能领40块钱优惠劵了你领了吗，今天我又试了下优惠劵下单，还是没有使用，条件肯定达到了只要满399就可以

**Comment by sari3l** [comment]
优惠券我看下，毕竟之前太少，没法好好测试

**Comment by sari3l** [comment]
> 老哥山姆能领40块钱优惠劵了你领了吗，今天我又试了下优惠劵下单，还是没有使用，条件肯定达到了只要满399就可以

测试是正常使用的

**Comment by JimmyABZ** [comment]
<img width="560" alt="image" src="https://user-images.githubusercontent.com/105157016/169683656-662975c5-f194-4475-bec2-29cbd00a6c2b.png">

**Comment by JimmyABZ** [comment]
那我怎么就是用不了呢，选择了后，刷出运力，自动下单后是没有使用的

**Comment by sari3l** [comment]
不清楚，我测试买了两块牛排生效的

**Comment by JimmyABZ** [comment]
选项里【 0】的空格会有影响吗

**Comment by sari3l** [comment]
<img alt="image" width="560" src="https://user-images.githubusercontent.com/105157016/169683656-662975c5-f194-4475-bec2-29cbd00a6c2b.png">

你这样就已经选择了
