### ISSUE TITLE
鉴权过期

### ISSUE THREAD

**Issue by xw5e** [sari3l/sams_helper#74]
原版可以用 但是这个改版就是一直说过期

**Comment by sari3l** [comment]
数据包截获发一下吧

**Comment by sari3l** [comment]
已添加设备 ID 选填

**Comment by hydra77** [comment]
感觉不是设备数量的问题，因为如果是设备数量的问题，那么原版应该也是应该不能用的。

**Comment by sari3l** [comment]
> 感觉不是设备数量的问题，因为如果是设备数量的问题，那么原版应该也是应该不能用的。

```shell
curl -H 'auth-token: xxxxx' https://api-sams.walmartmobile.cn/api/v1/sams/sams-user/receiver_address/address_list
```

这种情况只能自己抓包覆盖header

**Comment by xw5e** [comment]
对 我试过了 加了id还是不行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月9日(周一) 下午4:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sari3l/sams_helper] 鉴权过期 (Issue #74)




  
感觉不是设备数量的问题，因为如果是设备数量的问题，那么原版应该也是应该不能用的。
  curl -H 'auth-token: xxxxx' https://api-sams.walmartmobile.cn/api/v1/sams/sams-user/receiver_address/address_list
 
这种情况只能自己抓包覆盖header

**Comment by sari3l** [comment]
> 对 我试过了 加了id还是不行
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年5月9日(周一) 下午4:23 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [sari3l/sams_helper] 鉴权过期 (Issue #74) 感觉不是设备数量的问题，因为如果是设备数量的问题，那么原版应该也是应该不能用的。 curl -H 'auth-token: xxxxx' https://api-sams.walmartmobile.cn/api/v1/sams/sams-user/receiver_address/address_list 这种情况只能自己抓包覆盖header — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

1. 直接替换所有header
2. 问客服是否已经绑定上限

**Comment by sari3l** [comment]
@hydra77 #12 你当时是改了什么么

**Comment by xw5e** [comment]
> diff同一个接口请求的数据包

小白= =不知道怎么截获数据包

**Comment by sari3l** [comment]
> > diff同一个接口请求的数据包
> 
> 小白= =不知道怎么截获数据包

... = = 那你那里来的token

**Comment by xw5e** [comment]
> > 对 我试过了 加了id还是不行
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年5月9日(周一) 下午4:23 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [sari3l/sams_helper] 鉴权过期 (Issue #74) 感觉不是设备数量的问题，因为如果是设备数量的问题，那么原版应该也是应该不能用的。 curl -H 'auth-token: xxxxx' https://api-sams.walmartmobile.cn/api/v1/sams/sams-user/receiver_address/address_list 这种情况只能自己抓包覆盖header — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 1. 直接替换所有header
> 2. 问客服是否已经绑定上限
> 3. 可以的话你邮件发我token，我本地测试下

发你新浪邮箱了

**Comment by sari3l** [comment]
🤦‍♂️此issue完结，配置里`<>`没删
