### ISSUE TITLE
很抱歉，您提交的请求可能对网站造成威

### ISSUE THREAD

**Issue by Manchuker1120** [sari3l/sams_helper#75]
很抱歉，您提交的请求可能对网站造成威胁，请求已被管理员设置的策略阻断</h1><p class="text1">本页面为<span class="text-color">腾讯T-Sec Web应用防火墙(WAF)</span>默认提示页面，如有疑问请联系网站管理员并提供UUID信息</p><p class="text2">您的请求UUID为

跑的时间太久，被云waf阻断了。

**Comment by sari3l** [comment]
等半刻钟到半小时
