### ISSUE TITLE
早高峰期间一直出现“检查购物车失败”

### ISSUE THREAD

**Issue by SnoopyGo** [sari3l/sams_helper#77]
早上8点开始一直出现【检查购物车失败】😢，低峰期9点过后运行就不会出现。

**Comment by SnoopyGo** [comment]
> > 早上8点开始一直出现【检查购物车失败】😢，低峰期9点过后运行就不会出现。
> 
> 估摸网络不堪重负，都在跑脚本或程序了。。

好的吧，谢谢作者大哥！

**Comment by sari3l** [comment]
> > > 早上8点开始一直出现【检查购物车失败】😢，低峰期9点过后运行就不会出现。
> > 
> > 
> > 估摸网络不堪重负，都在跑脚本或程序了。。
> 
> 好的吧，谢谢作者大哥！

理论上可以试试代理到外地，因为走的腾讯云
