### ISSUE TITLE
提示RECEIVER_TIME_EMPTY 收货时间为空

### ISSUE THREAD

**Issue by connermo** [sari3l/sams_helper#8]
如题，提交订单的时候显示:
########## 提交订单中【11:00:42】 ###########
[!] code: RECEIVER_TIME_EMPTY 收货时间为空
不知道为什么，谢谢！

**Comment by sari3l** [comment]
不好意思，请先使用v1.0.2版本，应该没有问题，v1.0.3上午山姆更新导致回滚了

**Comment by sari3l** [comment]
你好，请尝试使用最新v1.0.4，此问题已修正

**Comment by connermo** [comment]
是用的代码更新执行，好像还是一样错误。

**Comment by sari3l** [comment]
v1.0.5已修复，源自网络崩溃时的异常没有捕获，实际没有运力释放
