### ISSUE TITLE
你好，山姆配送地址新增上海履约中心，脚本会失效，购物车会没有货品，能帮忙改下吗

### ISSUE THREAD

**Issue by yangying913** [sari3l/sams_helper#80]

**Comment by sari3l** [comment]
上海履约中心大概位置是哪里呢，我测试一下，另外早午抢购需要开启`updateStoreForce`

**Comment by 51033044** [comment]
现有程序是可以的，今早我成功预定了  上海履约中心 的地址。 如楼上所说，可能没有开启 `updateStoreForce `

**Comment by yangying913** [comment]
> 现有程序是可以的，今早我成功预定了 上海履约中心 的地址。 如楼上所说，可能没有开启 `updateStoreForce`

哦，原来如此，我明天在试试
