### ISSUE TITLE
早上无货状态下开启程序，等商店极速达上线不会自动下单的问题。

### ISSUE THREAD

**Issue by yygxh** [sari3l/sams_helper#82]
前一天的购物车没有清空，早上7:50左右开启，发现8:09商店极速达上线，并且商品上货后不会自动下单，需要关闭程序重新打开。updateStoreForce:已设置为true。

**Comment by sari3l** [comment]
我大概理解这个问题的原因，因为已有货物没有触发异常，导致没有重新检查商店状态，这个问题加个线程判断一下

**Comment by sari3l** [comment]
v1.2.3理论修复，期待反馈
