### ISSUE TITLE
想问下

### ISSUE THREAD

**Issue by meviyysss** [sari3l/sams_helper#85]
如何实现只是监控极速达的开门可配送的情况  不需要自动下单  然后实现推送手机

**Comment by sari3l** [comment]
没太理解，如果是单纯监控商店就直接GetStoreList检测StoreType然后notice

**Comment by meviyysss** [comment]
对，只监控运力 但不知道该怎么操作

**Comment by sari3l** [comment]
在getCapacityData，但是需要提交订单模板 ID
