### ISSUE TITLE
山姆极速达改变策略了？

### ISSUE THREAD

**Issue by xiaoNiuNew** [sari3l/sams_helper#87]
不同账号，购物车货物上架的时间不一样？不知道有其他人遇到没。已经2天这种情况。
updateStoreForce是true。

**Comment by xiaoNiuNew** [comment]
版本是1.2.2

**Comment by sari3l** [comment]
暂未遇到，等其他反馈

**Comment by guhan121** [comment]
封城期间做的？

**Comment by alvingzd** [comment]
> 不同账号，购物车货物上架的时间不一样？不知道有其他人遇到没。已经2天这种情况。 updateStoreForce是true。

感觉是释放购物车的时间不一样。
