### ISSUE TITLE
今天两点的全城配送，报这个：获取履约配送信息异常，有人知道是什么原因吗？

### ISSUE THREAD

**Issue by Felix3615** [sari3l/sams_helper#92]

**Comment by sari3l** [comment]
能不能至少把运行截图或者配置信息发上来？

**Comment by Felix3615** [comment]
> 能不能至少把运行截图或者配置信息发上来？

case "GET_DELIVERY_INFO_ERROR":
			return conf.GetDeliveryErr, gjson.Result{}
忘记截图了，报的这个错误码

**Comment by sari3l** [comment]
...你是觉得看这个能解决问题么

**Comment by sari3l** [comment]
还有我看你sams也发了个这问题，你是两个版本都运行了都报这个错误？

**Comment by Felix3615** [comment]
> 还有我看你sams也发了个这问题，你是两个版本都运行了都报这个错误？

是的，今天运行突然就报这个了，之前从没有过，报错后，又去运行sams试了一下，也是这个错误

**Comment by Felix3615** [comment]
明天再试试，如果还是这个，我再截个图上来

**Comment by sari3l** [comment]
> 明天再试试，如果还是这个，我再截个图上来

ok

**Comment by iscod** [comment]
@sari3l，https://github.com/robGoods/sams/commit/e7b36fdbc921c1d8999e731ab34d96cdf1337779
