### ISSUE TITLE
提交订单提示未知失败

### ISSUE THREAD

**Issue by york11** [sari3l/sams_helper#94]
![64380161e7aeda9f7157f1d73552119](https://user-images.githubusercontent.com/104375166/170672997-21c5c938-023b-426b-8717-fbaa74d232b6.jpg)

**Comment by sari3l** [comment]
未知失败是山姆服务器的问题

**Comment by york11** [comment]
这是昨天的情况，下单失败，今天下单成功后脚本显示没有商品，随后前往山姆APP，提示订单超时未付款，订单被取消。很遗憾没有脚本截图。具体下单时间为14:01:10，收到取消通知在10秒钟内。非常奇怪 是不是山姆检测到了脚本的运行？非常感谢作者的回复以及开发。
![ae661c050a59630d02c86a074027399](https://user-images.githubusercontent.com/104375166/170674225-009d5210-83ff-466b-b4b8-7e491d82c65f.jpg)
![8eeab8ce660e1c80674866fe3cbba76](https://user-images.githubusercontent.com/104375166/170674238-6d562700-9e48-4a59-b98e-3e276e11a00d.jpg)

**Comment by york11** [comment]
另外，我的脚本版本比较老，为1.2.2版本，是不是旧版的问题导致的？明天更新到最新试一下，谢谢作者大哥。

**Comment by sari3l** [comment]
山姆在网络拥堵情况，是会有显示提交失败但是下单成功的样子，很小很小的概率，1.2.2其实不低了， 后续不是非必要更新
其实有的 BUG 是很奇怪的，没有数据包不好处理

**Comment by sari3l** [comment]
另外爆破模式在拥堵情况下可能也是诱因之一，毕竟是利用了山姆的 BUG

**Comment by sari3l** [comment]
另外上面的图的意思是下单成功但是 10 秒内被取消？

**Comment by york11** [comment]
是的 订单成功下了，然后马上就收到取消短信，显示被取消

**Comment by sari3l** [comment]
> 是的 订单成功下了，然后马上就收到取消短信，显示被取消

这种还没遇到过，不知道是不是bruteCapacity造成还是没货砍单，毕竟用的 BUG，如果急需物资的话，建议先关闭，其次就再继续保持开启下单试试还会不会砍
