### ISSUE TITLE
感谢作者

### ISSUE THREAD

**Issue by york11** [sari3l/sams_helper#95]
在上海疫情最严重的时候作者大哥的程序帮助了我们无数的人，一直的更新与解答让我倍受感激，如今的上海已经解封，任然记得作者的无私奉献，在此向作者以及无数为这次一起做出贡献的人们表示最真挚的感谢与感激，此项目终于可以停更了，愿不再启用。感谢！

**Comment by york11** [comment]
一瓶水钱 祝安好

**Comment by sari3l** [comment]
谢谢～
